package com.example.lovable_clone.entity;

import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.FieldDefaults;

import java.time.Instant;


/**
 * UsageLog represents a single usage event generated by a user action.
 * It is used for tracking AI usage, token consumption, execution duration,
 * billing, analytics, and abuse detection across projects.
 *
 * This entity is append-only and should never be updated once created.
 */
@Entity
@Table(
        name = "usage_log",
        indexes = {
                @Index(name = "idx_usage_log_user", columnList = "user_id"),
                @Index(name = "idx_usage_log_project", columnList = "project_id"),
                @Index(name = "idx_usage_log_action", columnList = "action"),
                @Index(name = "idx_usage_log_created_at", columnList = "created_at")
        }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@FieldDefaults(level = AccessLevel.PRIVATE)
public class UsageLog {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    Long id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    User user;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "project_id")
    Project project;

    @Column(nullable = false, length = 100)
    String action;   // e.g. CHAT_COMPLETION, PREVIEW_START, FILE_GENERATION

    @Column(name = "token_used")
    Integer tokenUsed;   // number of AI tokens consumed by this action

    @Column(name = "duration_ms")
    Integer durationMs;  // execution time in milliseconds

    @Column(name = "meta_data", columnDefinition = "TEXT")
    String metaData;     // JSON metadata (model, prompt size, error info, etc.)

    @Column(name = "created_at", nullable = false, updatable = false)
    Instant createdAt;

    @PrePersist
    protected void onCreate() {
        this.createdAt = Instant.now();
    }
}
